# Generated by Django 5.0.6 on 2024-06-26 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('subject', models.TextField(max_length=30)),
                ('context_of_comment', models.TextField(max_length=500)),
                ('phone', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Pets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('type', models.CharField(choices=[('cat', 'cat'), ('dog', 'dog'), ('bird', 'bird'), ('rat', 'rat'), ('snake', 'snake'), ('other', 'other')], default='others', max_length=100)),
                ('breed', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('age', models.IntegerField(default=0)),
                ('place', models.CharField(max_length=50)),
                ('date_of_add', models.DateTimeField()),
            ],
        ),
    ]
