# Generated by Django 5.0.6 on 2024-06-26 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pets',
            name='date_of_add',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='pets',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='photos/'),
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='photos/')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets_app.pets')),
            ],
        ),
    ]
